name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - opendistro-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout security kibana
      uses: actions/checkout@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.x
      
    - name: Test and Build
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
        export NVM_HOME="$HOME/.nvm"
        ./build.sh
        artifact_path=`ls $(pwd)/target/releases/opendistro_security_kibana_plugin-*.zip`
        artifact_name=`basename $artifact_path`
        echo ::set-env name=ARTIFACT_PATH::$artifact_path
        echo ::set-env name=ARTIFACT_NAME::$artifact_name
    
    - name: Upload Workflow Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_PATH }}
